services:
  # Banco de Dados PostgreSQL
  db:
    image: postgres:16-alpine
    container_name: nps-db
    environment:
      POSTGRES_DB: npsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - nps_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d npsdb"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - nps-network

  # Backend API (NestJS)
  api:
    build:
      context: ./relatorio_nps_backend
      dockerfile: Dockerfile
    container_name: nps-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:postgres@db:5432/npsdb?schema=public
      PORT: 3001
    ports:
      - "3001:3001"
    restart: on-failure
    networks:
      - nps-network

  # Frontend (Next.js)
  frontend:
    build:
      context: ./relatorio_nps_frontend
      dockerfile: Dockerfile
    container_name: nps-frontend
    depends_on:
      - api
    environment:
      NODE_ENV: production
      API_URL: http://api:3001
    ports:
      - "3000:3000"
    restart: on-failure
    networks:
      - nps-network

volumes:
  nps_pgdata:

networks:
  nps-network:
    driver: bridge